const cityList = [
    "Tokyo, Japan",
    "Delhi, Indi",
    "Shanghai, China",
    "São Paulo, Brazil",
    "Mexico City, Mexico",
    "Cairo, Egypt",
    "Mumbai, India",
    "Beijing, China",
    "Dhaka, Bangladesh",
    "Osaka, Japan",
    "New York City, United States",
    "Karachi, Pakistan",
    "Buenos Aires, Argentina",
    "Chongqing, China",
    "Istanbul, Turkey",
    "Kolkata, India",
    "Manila, Philippines",
    "Lagos, Nigeria",
    "Rio de Janeiro, Brazil",
    "Tianjin, China",
    "Kinshasa, Democratic Republic of the Congo",
    "Guangzhou, China",
    "Los Angeles, United States",
    "Moscow, Russia",
    "Shenzhen, China",
    "Lahore, Pakistan",
    "Bangalore, India",
    "Paris, France",
    "Bogotá, Colombia",
    "Jakarta, Indonesia",
    "Washington DC, United States",
    "Chicago, United States"
]
export default cityList